.TH rfilter "1" "2015" "" ""

.SH "NAME"
rfilter \-\- filter stdin by a JavaScript regex

.SH SYNOPSIS

[
.I stdin
]
.B | rfilter
[
.I regex
]

.SH VERSION
1.0.0

.SH DESCRIPTION

Filter stdin by a JavaScript Regular Expression and output to stdout.
Implies the 'm' JavaScript regex flag.

Kinda like 'grep' but uses JavaScript regex syntax.
